### ISSUE TITLE
Build failure due to test errors

### ISSUE THREAD

**Issue by datapresso** [tamingtext/book#19]
Hello,

I have followed the readme to build the code downloaded from master branch yesterday. I keep getting the following errors during the test phase of maven build.  It seems only 3 of the unit tests failed. I want to check if these are known issues or if there is any workaround so that I can complete the build and test out the sample QA system.

I am using Windows 2008 R2,  JDK 1.7.0_05, Maven 3.2.2

Thanks
-Jimmy

---
##  T E S T S

Running com.tamingtext.carrot2.Carrot2ExampleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.192 sec
Running com.tamingtext.classifier.bayes.BayesUpdateRequestProcessorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.566 sec
Running com.tamingtext.classifier.bayes.ExtractTrainingDataTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.961 sec <<< FAILURE!
Running com.tamingtext.classifier.mlt.MoreLikeThisQueryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.565 sec
Running com.tamingtext.fuzzy.LevenshteinDistanceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.171 sec
Running com.tamingtext.fuzzy.OverlapMeasuresTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.737 sec
Running com.tamingtext.fuzzy.TrieNodeTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.182 sec
Running com.tamingtext.mahout.VectorExamplesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.134 sec
Running com.tamingtext.opennlp.AnswerTypeTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.956 sec <<< FAILURE!
Running com.tamingtext.opennlp.ChunkParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.611 sec
Running com.tamingtext.opennlp.NameFinderTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.591 sec
Running com.tamingtext.opennlp.ParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.751 sec
Running com.tamingtext.opennlp.POSTaggerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.843 sec
Running com.tamingtext.qa.PassageRankingComponentTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 50.974 sec
Running com.tamingtext.qa.QATest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 53.369 sec <<< FAILURE!
Running com.tamingtext.sentences.SentenceDetectionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.329 sec
Running com.tamingtext.snowball.SnowballStemmerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.189 sec
Running com.tamingtext.solr.SolrJTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.192 sec
Running com.tamingtext.texttamer.solr.NameFilterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.377 sec
Running com.tamingtext.texttamer.solr.SentenceTokenizerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.457 sec
Running com.tamingtext.tika.TikaTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.889 sec
Running com.tamingtext.util.StringUtilTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.221 sec

Results :

Tests in error: 

Tests run: 43, Failures: 0, Errors: 4, Skipped: 0

**Comment by MrXemiu** [comment]
I was able to address the errors in com.tamingtext.opennlp.AnswerTypeTest and Running com.tamingtext.qa.QATest by renaming the index.* files to *.idx and data.* to *.data in ~TT_HOME/WordNet-3.0/dict/.  For example, data.adj => adj.dat and index.adj => adj.idx.

The issue with com.tamingtext.classifier.bayes.ExtractTrainingDataTest seems to be a permissions issue.  In my case it looks like:

java.io.IOException: Failed to set permissions of path: \tmp\hadoop-GChavez\mapred\staging\GChavez-212503113\.staging to 0700

I'm still working on solving this one.

**Comment by MrXemiu** [comment]
From what I can tell, the issue is the version of Hadoop that the Mahout dependency in this project.  See https://issues.apache.org/jira/browse/HADOOP-7682

TamingText depends on Mahout 0.6, the latest version is 0.11.

I'm a Java noob and I have no idea how to go about trying to update these dependencies.  Otherwise, I'd fork this repo, update it, and submit a pull request.  If anyone wants to point me to some resources that will educate me, I'd appreciate it.  Otherwise I'll keep beating my head against it until I figure it out.

**Comment by antxa** [comment]
Hi,
I'm also getting an error during the test phase for AnswerTypeTest, but for a different reason.

_Running com.tamingtext.opennlp.AnswerTypeTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.786 sec <<< FAILURE!_

I am using Ubuntu, JDK 1.8 and Maven 3.3.9. But I tried with older Java and Maven versions and I got the same error.

Check the test error log below.

Thanks a lot,
Arantxa


_Test set: com.tamingtext.opennlp.AnswerTypeTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.786 sec <<< FA
ILURE!
demonstrateATCG(com.tamingtext.opennlp.AnswerTypeTest)  Time elapsed: 1.686 sec 
 <<< ERROR!
java.lang.NumberFormatException: For input string: "NUMBER_OF_VERB_FRAMES"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.
java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at net.didion.jwnl.data.VerbFrame.initialize(VerbFrame.java:22)
	at opennlp.tools.coref.mention.JWNLDictionary.<init>(JWNLDictionary.java
:60)
	at com.tamingtext.qa.AnswerTypeContextGenerator.<init>(AnswerTypeContext
Generator.java:58)
	at com.tamingtext.opennlp.AnswerTypeTest.demonstrateATCG(AnswerTypeTest.
java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces_
