### ISSUE TITLE
Lazy loading error - Chapter 3

### ISSUE THREAD

**Issue by bigtunacan** [tamingtext/book#21]
When trying to run the curl samples against the Word docs from Chapter 3 a Lazy Loading error occurs.

    curl "http://localhost:8983/solr/update/extract?&extractOnly=true" \
       -F "myfile=@src/test/resources/sample-word.doc"

Causes error similar to the following...

    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
    <title>Error 500 lazy loading error
    
    org.apache.solr.common.SolrException: lazy loading error
      at org.apache.solr.core.RequestHandlers$LazyRequestHandlerWrapper.getWrappedHandler(RequestHandlers.java:260)
      at org.apache.solr.core.RequestHandlers$LazyRequestHandlerWrapper.handleRequest(RequestHandlers.java:242)
      at org.apache.solr.core.SolrCore.execute(SolrCore.java:1376)
      at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:365)
      at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:260)
      at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
      at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
      at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
      at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
      at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
      at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
      at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
      at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
      at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
      at org.mortbay.jetty.Server.handle(Server.java:326)
      at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
      at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
      at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
      at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
      at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
      at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
      at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
    Caused by: org.apache.solr.common.SolrException: Error loading class 'solr.extraction.ExtractingRequestHandler'
      at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:394)
      at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:419)
      at org.apache.solr.core.SolrCore.createRequestHandler(SolrCore.java:455)
      at org.apache.solr.core.RequestHandlers$LazyRequestHandlerWrapper.getWrappedHandler(RequestHandlers.java:251)
      ... 21 more
    Caused by: java.lang.ClassNotFoundException: solr.extraction.ExtractingRequestHandler
      at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
      at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
      at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
      at java.lang.Class.forName0(Native Method)
      at java.lang.Class.forName(Class.java:270)
      at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:378)
      ... 24 more
    </title>
    </head>

**Comment by chalia75** [comment]
I have similar issue. Any clue how to solve it?

**Comment by chalia75** [comment]
I have been using the downloaded zip instead of checking out here. I go through change logs for this repository and find it out that it has been fixed. If you checking out here, it should work. Or you manually modify the apache-solr/example/solr/solrconfig.xml by adding following lines: 

    <lib dir="../lib" regex="taming-text-.*\.jar"/>
    <lib dir="../lib/dependency" />

    <lib dir="../../../target" regex="taming-text-.*\.jar" />
    <lib dir="../../../target/dependency" rexex=".*\.jar" />
